src/Entity/Personne.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\InheritanceType;

/**
 * @Entity
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="Profil", type="string")
 * @DiscriminatorMap({"personne" = "Personne", "artiste" = "Artiste","professionnel" = "Professionnel"})
 */
class Personne
{
    /**
     * @var int
     *
     * @ORM\Column(name="Id_Personne", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idPersonne;

    /**
     * @var string
     *
     * @ORM\Column(name="Nom", type="string", length=50, nullable=false)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="Prenom", type="string", length=50, nullable=false)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="Ville", type="string", length=50, nullable=false)
     */
    private $ville;

    /**
     * @var string
     *
     * @ORM\Column(name="Adresse", type="string", length=50, nullable=false)
     */
    private $adresse;

    /**
     * @var string
     *
     * @ORM\Column(name="Email", type="string", length=50, nullable=false)
     */
    private $email;

    /**
     * @var string|null
     *
     * @ORM\Column(name="Telephone", type="string", length=50, nullable=true)
     */
    private $telephone;

    /**
     * @var \Civilité
     *
     * @ORM\ManyToOne(targetEntity="Civilite")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Id_Civilite", referencedColumnName="Id_Civilite",nullable=false)
     * })
     */
    private $Civilite;

    public function getIdPersonne(): ?int
    {
        return $this->idPersonne;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getCivilite(): ?Civilite
    {
        return $this->Civilite;
    }

    public function setCivilite(?Civilite $Civilite): self
    {
        $this->Civilite = $Civilite;

        return $this;
    }


    /**
     * @ORM\OneToMany(targetEntity=Postuler::class, mappedBy="Personne", orphanRemoval=true)
     */
    private $Postulations;

    public function __construct()
    {
        $this->Postulations = new ArrayCollection();
    }

    /**
     * @return Collection<int, Postuler>
     */
    public function getPostulations(): Collection
    {
        return $this->Postulations;
    }

    public function addPostulation(Postuler $postulation): self
    {
        if (!$this->Postulations->contains($postulation)) {
            $this->Postulations[] = $postulation;
            $postulation->setPersonne($this);
        }

        return $this;
    }

    public function removePostulation(Postuler $postulation): self
    {
        if ($this->Postulations->removeElement($postulation)) {
            // set the owning side to null (unless already changed)
            if ($postulation->getPersonne() === $this) {
                $postulation->getPersonne(null);
            }
        }

        return $this;
    }



}

src/Controller/MonController.php
<?php

namespace App\Controller;

use App\Entity\Artiste;
use App\Entity\Casting;
use App\Entity\Postuler;
use App\Repository\CastingRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Faker\Factory;
use Symfony\Component\Security\Core\Security;

class MonController extends AbstractController
{
    private Security $security;
    public function __construct(Security $security){
        $this->security = $security;
    }
    #[Route('/', name: 'app_mon')]
    public function index(ManagerRegistry $doctrine, Request $request): Response
    {
        $em = $doctrine->getManager();
        $search = '';
        //controle de la rechercher
        if (isset($_GET['s'])) {
            $search = $request->query->get('s');
        }
        if($request->query->get("s")){
            $search = $request->query->get("s");
        }
        if(strlen((trim($search)) !=0)){
            $castings = $em->createQuery('SELECT o FROM App\Entity\Casting o WHERE o.intitule LIKE :search');
            $castings->setParameter('search','%'.$search.'%');
            $castings = $castings->getResult();
        }
        else{
            $castings = $em->getRepository(Casting::class);
            $castings = $castings->findAll();
        }
        if(empty($castings)){
            $bool = true;
        }else {
            $bool = false;
        }
        $limit = 12;

        $page = (int)$request->query->get("page", 1);
        $castingRepository = $em->getRepository(Casting::class);
        $castings = $castingRepository->getPaginateCastings($page, $limit);

        $total = $castingRepository->getTotalCastings();

        return $this->render('mon/index.html.twig', [
            'castings' => $castings,
            'total' => $total,
            'page'=>$page,
            'limit'=>$limit,
        ]);
    }
    public function footer(ManagerRegistry $doctrine, Request $request): Response
    {
        //controle de la rechercher
        if (isset($_GET['s'])) {
            $search = $request->query->get('s');
        }


        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();


        return $this->render('layout/footer.html.twig', [
            'castings' => $castings,
        ]);


    }

    #[Route('/casting/{id}', name: 'app_casting')]
    public function casting(ManagerRegistry $doctrine, $id): Response
    {
        //Récupération du casting
        $em = $doctrine->getManager();
        $query = $em->createQuery('SELECT casting FROM App\Entity\Casting casting WHERE casting.idCasting = :id');
        $query->setParameter('id', $id);
        $casting = $query->getResult();


        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();
        return $this->render('mon/casting.html.twig', [
            'casting' => $casting[0],
            'castings' => $castings,
        ]);


    }

    #[Route('/cinema', name: 'app_cinema')]
    public function cinema(ManagerRegistry $doctrine): Response
    {
        //Récupération des castings cinéma
        $em = $doctrine->getManager();
        $query = $em->createQuery('
        SELECT casting 
        FROM App\Entity\Casting casting
        WHERE casting.Metier = 1
        OR casting.Metier = 2
        OR casting.Metier = 3');
        $castingcinema = $query->getResult();

        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();


        return $this->render('mon/cinema.html.twig', [
            'castingcinema' => $castingcinema,
            'castings' => $castings,
        ]);
    }
    #[Route('/musique', name: 'app_musique')]
    public function musique(ManagerRegistry $doctrine): Response
    {
        //Récupération des castings musique
        $em = $doctrine->getManager();
        $query = $em->createQuery('SELECT casting 
        FROM App\Entity\Casting casting
        WHERE casting.Metier = 4
        OR casting.Metier = 5
        OR casting.Metier = 6
        OR casting.Metier = 7');
        $castingmusique = $query->getResult();

        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();
        return $this->render('mon/musique.html.twig', [
            'castingmusique' => $castingmusique,
            'castings' => $castings,
        ]);
    }
    #[Route('/danse', name: 'app_danse')]
    public function danse(ManagerRegistry $doctrine): Response
    {
        //Récupération des castings danse
        $em = $doctrine->getManager();
        $query = $em->createQuery('SELECT casting 
        FROM App\Entity\Casting casting
        WHERE casting.Metier = 8
        OR casting.Metier = 9');
        $castingdanse = $query->getResult();

        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();
        return $this->render('mon/danse.html.twig', [
            'castingdanse' => $castingdanse,
            'castings' => $castings,
        ]);
    }
    #[Route('/theatre', name: 'app_theatre')]
    public function theatre(ManagerRegistry $doctrine): Response
    {
        //Récupération des castings theatre
        $em = $doctrine->getManager();
        $query = $em->createQuery('SELECT casting 
        FROM App\Entity\Casting casting
        WHERE casting.Metier = 10
        OR casting.Metier = 11
        OR casting.Metier = 12');
        $castingtheatre = $query->getResult();

        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();
        return $this->render('mon/theatre.html.twig', [
            'castingtheatre' => $castingtheatre,
            'castings' => $castings,
        ]);
    }
    #[Route('/profil', name: 'app_profil')]
    public function profil(ManagerRegistry $doctrine): Response
    {


        //Récupération des casting
        $em = $doctrine->getManager();
        $castingsREPO = $em->getRepository(Casting::class);
        $castings = $castingsREPO->findAll();

        //Récupération de l'artiste
        $artiste = $this->security->getUser();
        dump($artiste);

        $queryPostulations = $em->createQueryBuilder()
            ->select('p')
            ->from(Postuler::class,'p')
            ->where('p.Personne = :personne')
            ->setParameter('personne', $this->getUser()->getIdPersonne());
        $postulations = $queryPostulations->getQuery()->getResult();



        return $this->render('profil/profil.html.twig', [
            'castings' => $castings,
            'artiste' => $artiste,
            'postulations' => $postulations,
        ]);
    }
}

templates/mon/casting.html.twig
{% extends 'base.html.twig' %}

{% block title %}Megacasting{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>
    <div class="container">
    <div class="row">

    <div class="col-md-12 d-flex flex-wrap justify-content-around">
        <div class="col-md-6">
            <h1>{{ casting.intitule}}</h1>
            <img src="{{ asset('img/casting.jpg') }}" width="500">
        </div>
        <div class="col-md-6 mt-5">
            <p><u>Description du profil rechercher:</u> {{ casting.descriptionprofil }}</p>
            <p><u>Description du poste:</u> {{ casting.descriptionPoste }}</p>
            <p><u>Lieux:</u> {{ casting.localisation }}</p>
            <p><u>Contact:</u> {{ casting.Professionnel.civilite.genre}} {{ casting.Professionnel.nom}} {{ casting.Professionnel.prenom}} : {{ casting.coordonnees }}</p>
            <p><u>Type de contrat:</u> {{ casting.Contrat.libelle}}</p>
            <p><u>Type de métier:</u> {{ casting.Metier.libelle}}</p>
            {% if(is_granted("IS_AUTHENTICATED_FULLY")) %}
                <a type="" class="btn btn-success mt-5 p-4" style="margin-right: 20px";
                   href="{{ path('postuler', {'id': casting.idCasting}) }}"><b>POSTULER</b>
                </a>
            {% else %}
                <a type="button" class="btn btn-success mt-5 p-4" style="margin-right: 20px"
                   href="{{ url('app_register') }}"> <b>INCRIVEZ-VOUS</b> pour Postuler</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/mon/cinema.html.twig
{% extends 'base.html.twig' %}

{% block title %}Megacasting{% endblock %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>
<div class="container">
    <div class="row">

        <div class="col-md-12 d-flex flex-wrap justify-content-around">
            {% for casting in castingcinema %}
                {{ include('layout/littleCasting.html.twig', {'casting': casting})  }}
            {% endfor %}
        </div>
        {% endblock %}


templates/mon/danse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Megacasting{% endblock %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>
<div class="container">
    <div class="row">

        <div class="col-md-12 d-flex flex-wrap justify-content-around">
            {% for casting in castingdanse %}
                {{ include('layout/littleCasting.html.twig', {'casting': casting})  }}
            {% endfor %}
        </div>
        {% endblock %}


templates/mon/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Megacasting{% endblock %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>
<div class="container">
    <div class="row"></div>
        <div class="col-md-12 d-flex flex-wrap justify-content-around">
            {% for casting in castings %}
            {{ include('layout/littleCasting.html.twig', {'casting': casting}) }}
            {% endfor %}
            {% if castings == null  %}
                <p >Pas de correspondance à votre recherche </p>
            {% endif %}
            <div class="container mt-4">
                <ul class="pagination">
                    {% for item in 1..((total / limit)|round(0, 'ceil')) %}
                        <li class="page-item page-link">
                            <a href="?page={{ item }} ">{{ item }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endblock %}

templates/mon/musique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Megacasting{% endblock %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12 d-flex flex-wrap justify-content-around">
            {% for casting in castingmusique %}
                {{ include('layout/littleCasting.html.twig', {'casting': casting})  }}
            {% endfor %}
        </div>
        {% endblock %}


templates/mon/theatre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Megacasting{% endblock %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>
<div class="container">
    <div class="row">

        <div class="col-md-12 d-flex flex-wrap justify-content-around">
            {% for casting in castingtheatre %}
                {{ include('layout/littleCasting.html.twig', {'casting': casting})  }}
            {% endfor %}
        </div>
        {% endblock %}
